In [125]:
ls

datasets/  pandas_prac.ipynb*

In [126]:
import pandas as pd

df=pd.read_csv('datasets/wine+quality/winequality-white.csv', delimiter=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [128]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [129]:
df["quality"].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [130]:
df.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3345,6.8,0.18,0.24,9.8,0.058,64.0,188.0,0.99520,3.13,0.51,10.6,6
316,6.8,0.25,0.34,4.7,0.031,34.0,134.0,0.99270,3.21,0.38,10.6,6
4632,6.3,0.30,0.91,8.2,0.034,50.0,199.0,0.99394,3.39,0.49,11.7,6
4242,5.9,0.22,0.29,4.2,0.037,69.0,144.0,0.99214,3.13,0.74,10.8,7
1963,7.4,0.32,0.55,16.6,0.056,53.0,238.0,1.00170,2.96,0.58,8.7,6

In [131]:
df[['fixed acidity', 'volatile acidity', 'citric acid',"quality"]].head()

   fixed acidity  volatile acidity  citric acid  quality
0            7.0              0.27         0.36        6
1            6.3              0.30         0.34        6
2            8.1              0.28         0.40        6
3            7.2              0.23         0.32        6
4            7.2              0.23         0.32        6

In [132]:
df.loc[1 : 5 , ['fixed acidity', 'volatile acidity', 'citric acid',"quality"]]

   fixed acidity  volatile acidity  citric acid  quality
1            6.3              0.30         0.34        6
2            8.1              0.28         0.40        6
3            7.2              0.23         0.32        6
4            7.2              0.23         0.32        6
5            8.1              0.28         0.40        6

In [133]:
df.iloc[1 : 5 ,0:5]

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides
1            6.3              0.30         0.34             1.6      0.049
2            8.1              0.28         0.40             6.9      0.050
3            7.2              0.23         0.32             8.5      0.058
4            7.2              0.23         0.32             8.5      0.058

In [134]:
df[(df['quality']<5) & (df['fixed acidity']<6)].head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
115,5.5,0.485,0.00,1.5,0.065,8.0,103.0,0.9940,3.63,0.40,9.7,4
204,5.8,0.280,0.35,2.3,0.053,36.0,114.0,0.9924,3.28,0.50,10.2,4
250,5.9,0.210,0.28,4.6,0.053,40.0,199.0,0.9964,3.72,0.70,10.0,4
253,5.8,0.240,0.44,3.5,0.029,5.0,109.0,0.9913,3.53,0.43,11.7,3
259,5.8,0.360,0.38,0.9,0.037,3.0,75.0,0.9904,3.28,0.34,11.4,4

In [135]:
newdf=df.sort_values("quality", ascending=False)
newdf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
827,7.4,0.240,0.36,2.0,0.031,27.0,139.0,0.99055,3.28,0.48,12.5,9
820,6.6,0.360,0.29,1.6,0.021,24.0,85.0,0.98965,3.41,0.61,12.4,9
1605,7.1,0.260,0.49,2.2,0.032,31.0,113.0,0.99030,3.37,0.42,12.9,9
876,6.9,0.360,0.34,4.2,0.018,57.0,119.0,0.98980,3.28,0.36,12.7,9
774,9.1,0.270,0.45,10.6,0.035,28.0,124.0,0.99700,3.20,0.46,10.4,9
...,...,...,...,...,...,...,...,...,...,...,...,...
2373,7.6,0.480,0.37,1.2,0.034,5.0,57.0,0.99256,3.05,0.54,10.4,3
3409,6.2,0.230,0.35,0.7,0.051,24.0,111.0,0.99160,3.37,0.43,11.0,3
3265,4.2,0.215,0.23,5.1,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,3
3087,6.1,0.200,0.34,9.5,0.041,38.0,201.0,0.99500,3.14,0.44,10.1,3
3307,9.4,0.240,0.29,8.5,0.037,124.0,208.0,0.99395,2.90,0.38,11.0,3

In [136]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [137]:
df.duplicated().sum()

np.int64(937)

In [138]:
df.drop_duplicates(inplace=True)

In [139]:
df.duplicated().sum()

np.int64(0)

In [140]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6

In [141]:
df.rename(columns={'fixed acidity':'fixed_acidity', 'volatile acidity':'volatile_acidity', 'citric acid':'citric_acid' , "residual sugar":"residual_sugar" , "free sulfur dioxide":"free_sulfur_dioxide" , "total sulfur dioxide":"total_sulfur_dioxide" ,"total sulfur dioxide":"total_sulfur_dioxide"}, inplace=True)

In [142]:
df.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')

In [143]:
df["new_quality"]=df["quality"].apply(lambda x: "good" if x>=7 else "bad")
df[df["new_quality"]=="good"].count()

fixed_acidity           825
volatile_acidity        825
citric_acid             825
residual_sugar          825
chlorides               825
free_sulfur_dioxide     825
total_sulfur_dioxide    825
density                 825
pH                      825
sulphates               825
alcohol                 825
quality                 825
new_quality             825
dtype: int64

In [144]:
df.drop("new_quality", axis=1, inplace=True)

In [145]:
df.info()

<class 'pandas.DataFrame'>
Index: 3961 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         3961 non-null   float64
 1   volatile_acidity      3961 non-null   float64
 2   citric_acid           3961 non-null   float64
 3   residual_sugar        3961 non-null   float64
 4   chlorides             3961 non-null   float64
 5   free_sulfur_dioxide   3961 non-null   float64
 6   total_sulfur_dioxide  3961 non-null   float64
 7   density               3961 non-null   float64
 8   pH                    3961 non-null   float64
 9   sulphates             3961 non-null   float64
 10  alcohol               3961 non-null   float64
 11  quality               3961 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 402.3 KB

In [146]:
df.groupby("quality").mean()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,7.600000,0.333250,0.336000,6.392500,0.054300,53.325000,170.600000,0.994884,3.187500,0.474500,10.345000
4,7.139869,0.382157,0.305229,4.499346,0.050059,23.127451,124.127451,0.994199,3.185425,0.476667,10.197712
5,6.921745,0.303306,0.335957,6.941532,0.052323,36.002979,150.099574,0.995072,3.171779,0.482621,9.864182
6,6.819435,0.261630,0.338227,5.959787,0.045178,35.308166,136.460850,0.993722,3.196029,0.492355,10.646122
7,6.701089,0.265363,0.327358,4.523875,0.037556,33.851234,122.052975,0.992059,3.228462,0.502859,11.515844
8,6.609924,0.286794,0.335038,5.056489,0.036756,35.618321,122.034351,0.991745,3.235115,0.485878,11.880153
9,7.420000,0.298000,0.386000,4.120000,0.027400,33.400000,116.000000,0.991460,3.308000,0.466000,12.180000

In [147]:
df.pivot_table(index="quality", values=["fixed_acidity", "volatile_acidity", "citric_acid"], aggfunc="std")

         citric_acid  fixed_acidity  volatile_acidity
quality
3           0.081460       1.724743          0.140827
4           0.163940       1.101574          0.176209
5           0.140859       0.862071          0.103415
6           0.120617       0.853331          0.089767
7           0.082185       0.775123          0.092231
8           0.087217       0.822646          0.103862
9           0.082037       0.983362          0.057619

In [148]:
df["quality"] = df["quality"].apply(lambda x: x-2)

In [149]:
df["quality"].value_counts()

quality
4    1788
3    1175
5     689
2     153
6     131
1      20
7       5
Name: count, dtype: int64

In [150]:
df.pivot_table(index="quality", values=["fixed_acidity", "volatile_acidity", "citric_acid"], aggfunc="max")

         citric_acid  fixed_acidity  volatile_acidity
quality
1               0.47           11.8             0.640
2               0.88           10.2             1.100
3               1.00           10.3             0.905
4               1.66           14.2             0.965
5               0.74            9.2             0.760
6               0.74            8.2             0.660
7               0.49            9.1             0.360

In [151]:
df.corr(numeric_only=True)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
fixed_acidity,1.000000,-0.019214,0.298959,0.083620,0.024036,-0.058396,0.082425,0.266091,-0.431274,-0.017453,-0.110788,-0.124636
volatile_acidity,-0.019214,1.000000,-0.163228,0.098340,0.086287,-0.102471,0.102315,0.060603,-0.046954,-0.021150,0.046815,-0.190678
citric_acid,0.298959,-0.163228,1.000000,0.106269,0.132590,0.091681,0.122845,0.160076,-0.183015,0.049442,-0.076514,0.007065
residual_sugar,0.083620,0.098340,0.106269,1.000000,0.076091,0.306835,0.409583,0.820498,-0.165997,-0.020503,-0.398167,-0.117339
chlorides,0.024036,0.086287,0.132590,0.076091,1.000000,0.101272,0.191145,0.253088,-0.090573,0.017871,-0.356928,-0.217739
free_sulfur_dioxide,-0.058396,-0.102471,0.091681,0.306835,0.101272,1.000000,0.619437,0.294638,-0.007750,0.037932,-0.251768,0.010507
total_sulfur_dioxide,0.082425,0.102315,0.122845,0.409583,0.191145,0.619437,1.000000,0.536868,0.008239,0.136544,-0.446643,-0.183356
density,0.266091,0.060603,0.160076,0.820498,0.253088,0.294638,0.536868,1.000000,-0.063734,0.082048,-0.760162,-0.337805
pH,-0.431274,-0.046954,-0.183015,-0.165997,-0.090573,-0.007750,0.008239,-0.063734,1.000000,0.142353,0.093095,0.123829
sulphates,-0.017453,-0.021150,0.049442,-0.020503,0.017871,0.037932,0.136544,0.082048,0.142353,1.000000,-0.022850,0.053200
alcohol,-0.110788,0.046815,-0.076514,-0.398167,-0.356928,-0.251768,-0.446643,-0.760162,0.093095,-0.022850,1.000000,0.462869
quality,-0.124636,-0.190678,0.007065,-0.117339,-0.217739,0.010507,-0.183356,-0.337805,0.123829,0.053200,0.462869,1.000000

In [152]:
df.agg({
    "fixed_acidity": ["mean", "median", "max" , "min"],
    "residual_sugar": ["mean", "median", "max" , "min"]
})

        fixed_acidity  residual_sugar
mean         6.839346        5.914819
median       6.800000        4.700000
max         14.200000       65.800000
min          3.800000        0.600000

In [153]:
df.to_csv("datasets/wine+quality/winequality-white-edited.csv", index=False)