In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('datasets/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv', delimiter=',')

In [3]:
column_mapping = {
    'Timestamp': 'timestamp',
    'How old are you?': 'age',
    'What industry do you work in?': 'industry',
    'Job title': 'job_title',
    'If your job title needs additional context, please clarify here:': 'job_title_context',
    "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'annual_salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation',
    'Please indicate the currency': 'currency',
    'If "Other," please indicate the currency here: ': 'other_currency',
    'If your income needs additional context, please provide it here:': 'income_context',
    'What country do you work in?': 'country',
    "If you're in the U.S., what state do you work in?": 'state',
    'What city do you work in?': 'city',
    'How many years of professional work experience do you have overall?': 'total_experience_years',
    'How many years of professional work experience do you have in your field?': 'field_experience_years',
    'What is your highest level of education completed?': 'education_level',
    'What is your gender?': 'gender',
    'What is your race? (Choose all that apply.)': 'race'
}

df.rename(columns=column_mapping, inplace=True)

In [4]:
missing_pct = (
    df.isnull().sum()
    / len(df)
    * 100
).sort_values(ascending=False)

print(missing_pct)

other_currency             99.206321
income_context             89.182582
job_title_context          74.159374
additional_compensation    26.127626
state                      17.985331
education_level             0.853913
race                        0.698012
gender                      0.659037
industry                    0.304716
city                        0.301173
job_title                   0.017716
country                     0.007086
age                         0.000000
timestamp                   0.000000
currency                    0.000000
annual_salary               0.000000
total_experience_years      0.000000
field_experience_years      0.000000
dtype: float64

In [5]:
df.sample(5)

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,other_currency,income_context,country,state,city,total_experience_years,field_experience_years,education_level,gender,race
6978,4/27/2021 14:19:04,45-54,"Marketing, Advertising & PR",Administrative Services Manager,"Office administrator, EA, operational engineer...","82,000",5000.0,USD,NaN,NaN,USA,Oregon,Portland,31 - 40 years,31 - 40 years,College degree,Woman,White
16107,4/28/2021 17:32:19,45-54,Property or Construction,Land and planning manager,NaN,"52,500",NaN,GBP,NaN,NaN,United Kingdom,NaN,Truro,21 - 30 years,21 - 30 years,College degree,Man,White
27476,11/2/2021 18:58:54,35-44,Education (Higher Education),Postdoctoral Researcher,NaN,57000,0.0,USD,NaN,NaN,USA,California,Merced,8 - 10 years,5-7 years,PhD,Man,White
23446,5/2/2021 20:53:46,25-34,Computing or Tech,Engineering Leadership,NaN,93000,25000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,5-7 years,5-7 years,College degree,Man,White
18958,4/29/2021 5:52:41,35-44,Computing or Tech,Chief Technology Officer,NaN,"285,000",50000.0,USD,NaN,NaN,United States,New York,New York City,11 - 20 years,11 - 20 years,College degree,Man,White

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28223 entries, 0 to 28222
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                28223 non-null  str
 1   age                      28223 non-null  str
 2   industry                 28137 non-null  str
 3   job_title                28218 non-null  str
 4   job_title_context        7293 non-null   str
 5   annual_salary            28223 non-null  str
 6   additional_compensation  20849 non-null  float64
 7   currency                 28223 non-null  str
 8   other_currency           224 non-null    str
 9   income_context           3053 non-null   str
 10  country                  28221 non-null  str
 11  state                    23147 non-null  str
 12  city                     28138 non-null  str
 13  total_experience_years   28223 non-null  str
 14  field_experience_years   28223 non-null  str
 15  education_level          27982 non-null  str
 16  gender                   28037 non-null  str
 17  race                     28026 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

In [7]:
df.nunique()

timestamp                  25441
age                            7
industry                    1225
job_title                  14433
job_title_context           7029
annual_salary               4332
additional_compensation      849
currency                      11
other_currency               130
income_context              2988
country                      390
state                        138
city                        4875
total_experience_years         8
field_experience_years         8
education_level                6
gender                         5
race                          52
dtype: int64

In [8]:
df['annual_salary'] = (
    df['annual_salary']
    .astype(str)
    .str.replace(',', '', regex=False)
)

df['annual_salary'] = pd.to_numeric(
    df['annual_salary'],
    errors='coerce'
)

In [9]:
df['additional_compensation'] = pd.to_numeric(df['additional_compensation'], errors='coerce')

In [10]:
df.isnull().sum().sort_values(ascending=False)

other_currency             27999
income_context             25170
job_title_context          20930
additional_compensation     7374
state                       5076
education_level              241
race                         197
gender                       186
industry                      86
city                          85
job_title                      5
country                        2
age                            0
timestamp                      0
currency                       0
annual_salary                  0
total_experience_years         0
field_experience_years         0
dtype: int64

In [11]:
df[df['annual_salary'].isnull()]

Empty DataFrame
Columns: [timestamp, age, industry, job_title, job_title_context, annual_salary, additional_compensation, currency, other_currency, income_context, country, state, city, total_experience_years, field_experience_years, education_level, gender, race]
Index: []

In [12]:
df['annual_salary'].head()
df['annual_salary'].dtype

dtype('int64')

In [13]:
df['annual_salary'].isna().sum()

np.int64(0)

In [14]:
df[
    (df['annual_salary'].isna()) &
    (df['gender'] == 'Woman')
]

Empty DataFrame
Columns: [timestamp, age, industry, job_title, job_title_context, annual_salary, additional_compensation, currency, other_currency, income_context, country, state, city, total_experience_years, field_experience_years, education_level, gender, race]
Index: []

In [15]:
cols = [
    'gender',
    'race',
    'country',
    'currency',
    'education_level'
]

for col in cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False).head(20))

 gender
gender
Woman                            21427
Man                               5563
Non-binary                         747
Other or prefer not to answer      299
NaN                                186
Prefer not to answer                 1
Name: count, dtype: int64

 race
race
White                                                                              23274
Asian or Asian American                                                             1431
Black or African American                                                            707
Another option not listed here or prefer not to answer                               632
Hispanic, Latino, or Spanish origin                                                  613
Hispanic, Latino, or Spanish origin, White                                           385
Asian or Asian American, White                                                       344
NaN                                                                                  197
Black or African American, White                                                     123
Middle Eastern or Northern African, White                                             83
Middle Eastern or Northern African                                                    74
Native American or Alaska Native, White                                               68
White, Another option not listed here or prefer not to answer                         65
Native American or Alaska Native                                                      43
Black or African American, Hispanic, Latino, or Spanish origin                        28
Asian or Asian American, Hispanic, Latino, or Spanish origin, White                   15
Asian or Asian American, Hispanic, Latino, or Spanish origin                          14
Black or African American, Hispanic, Latino, or Spanish origin, White                 11
Asian or Asian American, Another option not listed here or prefer not to answer       11
Hispanic, Latino, or Spanish origin, Native American or Alaska Native                 11
Name: count, dtype: int64

 country
country
United States               9036
USA                         7963
US                          2620
Canada                      1576
United States                669
U.S.                         586
UK                           576
United Kingdom               551
USA                          468
Usa                          448
United States of America     431
Australia                    319
United states                209
usa                          187
Germany                      174
England                      134
united states                116
Us                           106
Ireland                      103
New Zealand                   95
Name: count, dtype: int64

 currency
currency
USD        23496
CAD         1677
GBP         1598
EUR          654
AUD/NZD      505
Other        175
CHF           37
SEK           37
JPY           23
ZAR           17
HKD            4
Name: count, dtype: int64

 education_level
education_level
College degree                        13570
Master's degree                        8899
Some college                           2097
PhD                                    1428
Professional degree (MD, JD, etc.)     1329
High School                             659
NaN                                     241
Name: count, dtype: int64

In [16]:
df['country'] = df['country'].replace({
    'USA': 'US',
    'United States': 'US',
    'United States of America': 'US',
    'U.S.': 'US',
    "U.S": 'US',
    'Usa': 'US',
    'usa': 'US',
    'United states': 'US',
    'Us': 'US',
    'UK': 'United Kingdom',
    'U.K.': 'United Kingdom',
    'England': 'United Kingdom',
})

df['country'].value_counts()

country
US                21608
Canada             1576
United Kingdom     1264
United States       669
USA                 468
                  ...
Thailand              1
Liberia               1
1                     1
Nigeria + UK          1
Zambia                1
Name: count, Length: 378, dtype: int64

In [17]:
missing_pct = (
    df.isnull().sum()
    / len(df)
    * 100
).sort_values(ascending=False)

print(missing_pct)

other_currency             99.206321
income_context             89.182582
job_title_context          74.159374
additional_compensation    26.127626
state                      17.985331
education_level             0.853913
race                        0.698012
gender                      0.659037
industry                    0.304716
city                        0.301173
job_title                   0.017716
country                     0.007086
age                         0.000000
timestamp                   0.000000
currency                    0.000000
annual_salary               0.000000
total_experience_years      0.000000
field_experience_years      0.000000
dtype: float64

In [18]:
df.drop(columns=['other_currency','income_context'], inplace=True)

In [19]:
df = df.drop_duplicates(subset=df.columns.difference(['timestamp']))

In [20]:
print(df.shape)  # Check new row count
print(df.duplicated(subset=df.columns.difference(['timestamp'])).sum())  # Should be 0

(28068, 16)
0

In [21]:
df.sample(5)

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,country,state,city,total_experience_years,field_experience_years,education_level,gender,race
28141,5/20/2025 8:41:07,25-34,Recruitment or HR,Data anlyst,NaN,15000,0.0,EUR,Spain,NaN,Madrid,2 - 4 years,2 - 4 years,Master's degree,Man,"Hispanic, Latino, or Spanish origin"
27537,11/26/2021 12:43:06,25-34,"Marketing, Advertising & PR",Community Managet,NaN,65000,NaN,USD,US,Oregon,Remote,5-7 years,1 year or less,College degree,Woman,White
21328,4/30/2021 3:12:37,25-34,Computing or Tech,Lead Software Engineer,NaN,159000,23850.0,USD,US,Washington,Seattle,8 - 10 years,8 - 10 years,College degree,Man,White
19261,4/29/2021 8:32:34,25-34,Health care,Care Worker,NaN,28000,0.0,GBP,Scotland,NaN,Isle of Lewis,5-7 years,5-7 years,Some college,Woman,White
15797,4/28/2021 17:19:22,25-34,Education (Higher Education),Facilitator,Training class instructor at a large factory,70000,0.0,USD,US,Washington,Everett,11 - 20 years,8 - 10 years,College degree,Man,White

In [22]:
df['annual_salary'].isna().sum()

np.int64(0)

In [23]:
categorical_cols = [
    'state',
    'education_level',
    'race',
    'gender',
    'industry',
    'city',
    'country',
    'job_title_context'
]

for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

In [24]:
df['additional_compensation'] = (
    df['additional_compensation']
    .fillna(0)
)

In [25]:
df = df.dropna(subset=['job_title'])

In [26]:
missing_pct = (
    df.isnull().sum()
    / len(df)
    * 100
).sort_values(ascending=False)

print(missing_pct)

timestamp                  0.0
age                        0.0
industry                   0.0
job_title                  0.0
job_title_context          0.0
annual_salary              0.0
additional_compensation    0.0
currency                   0.0
country                    0.0
state                      0.0
city                       0.0
total_experience_years     0.0
field_experience_years     0.0
education_level            0.0
gender                     0.0
race                       0.0
dtype: float64

In [27]:
df['annual_salary'].dtype

dtype('int64')

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 28063 entries, 0 to 28222
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                28063 non-null  str
 1   age                      28063 non-null  str
 2   industry                 28063 non-null  str
 3   job_title                28063 non-null  str
 4   job_title_context        28063 non-null  str
 5   annual_salary            28063 non-null  int64
 6   additional_compensation  28063 non-null  float64
 7   currency                 28063 non-null  str
 8   country                  28063 non-null  str
 9   state                    28063 non-null  str
 10  city                     28063 non-null  str
 11  total_experience_years   28063 non-null  str
 12  field_experience_years   28063 non-null  str
 13  education_level          28063 non-null  str
 14  gender                   28063 non-null  str
 15  race                     28063 non-null  str
dtypes: float64(1), int64(1), str(14)
memory usage: 3.6 MB

In [29]:
df[df["additional_compensation"]== 0].count()

timestamp                  15270
age                        15270
industry                   15270
job_title                  15270
job_title_context          15270
annual_salary              15270
additional_compensation    15270
currency                   15270
country                    15270
state                      15270
city                       15270
total_experience_years     15270
field_experience_years     15270
education_level            15270
gender                     15270
race                       15270
dtype: int64

In [30]:
df['race_clean'] = df['race'].apply(
    lambda x: 'Mixed Race'
    if isinstance(x, str) and ',' in x
    else x
)
df['race_clean'] = df['race_clean'].replace({
    'Another option not listed here or prefer not to answer':
    'Other or Prefer not to answer' , 
    "Unknown" : 'Other or Prefer not to answer',
})

df['race_clean'].value_counts()

race_clean
White                                 23150
Mixed Race                             1855
Asian or Asian American                1420
Other or Prefer not to answer           822
Black or African American               700
Middle Eastern or Northern African       73
Native American or Alaska Native         43
Name: count, dtype: int64

In [31]:
(
    df['race_clean']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

race_clean
White                                 82.49
Mixed Race                             6.61
Asian or Asian American                5.06
Other or Prefer not to answer          2.93
Black or African American              2.49
Middle Eastern or Northern African     0.26
Native American or Alaska Native       0.15
Name: proportion, dtype: float64

In [32]:
df["gender"]=df['gender'].replace({
     'Unknown' :'Other or prefer not to answer' , "Prefer not to answer" :'Other or prefer not to answer'
      
})

df['gender'].value_counts(dropna=False)

gender
Woman                            21316
Man                               5522
Non-binary                         742
Other or prefer not to answer      483
Name: count, dtype: int64

In [33]:
df['education_level'].value_counts(dropna=False)

education_level
College degree                        13504
Master's degree                        8851
Some college                           2076
PhD                                    1420
Professional degree (MD, JD, etc.)     1323
High School                             652
Unknown                                 237
Name: count, dtype: int64

In [34]:
df['industry'].value_counts(dropna=False)

industry
Computing or Tech                       4698
Education (Higher Education)            2474
Nonprofits                              2405
Health care                             1894
Government and Public Administration    1886
                                        ...
ABA                                        1
psychology                                 1
School                                     1
lifeguard                                  1
study                                      1
Name: count, Length: 1225, dtype: int64

In [35]:
df['industry'].value_counts().sample(50)

industry
Wealth advisor Research                                1
Nonprofits                                          2405
Software                                               7
Consumer Goods                                         5
Earth sciences                                         1
Academic Medicine                                      1
Libraries                                              2
Animal health industry                                 1
Analytics                                              1
Administrative Work                                    1
Pharmaceutical Manufacturing                           1
Biotech/Drug Development                               1
Veterinary                                             4
pharma / medical device design and manufacturing       1
Environmental health and safety                        1
Horticulture                                           1
Childcare                                              1
Business Services                                      1
Consumer Good (Toys)                                   1
Program management                                     1
Aviation                                               2
Museum (<20 employees)                                 1
Finance                                                1
Career & Technical Training                            1
Laundry and Rental                                     1
Consumer Goods Production                              1
Politics/Campaigns                                     1
Hospital                                               1
Biology/Research                                       1
Grocery Distribution                                   2
Educational publishing / ed tech                       1
Internet                                               2
Horticulture (Admin)                                   1
Counselling                                            1
Social Work                                          274
Libraries/Archives                                     1
CBD Manufacturing                                      1
Biomedical Research                                    8
Academia / Research                                    1
Wholesale/Distrbution                                  1
Biotechnology/Life Sciences                            1
Academic publishing                                    2
Government Relation                                    1
Apparel                                                1
Animal Care                                            1
Academic Scientific Research                           1
Public/Environmental Health                            1
IT                                                     6
Marketing, Advertising & PR                         1122
Medical Sciences                                       1
Name: count, dtype: int64

In [36]:
import pandas as pd

def clean_country(country):

    if pd.isna(country):
        return 'Unknown'

    country = str(country).strip().lower()

    # ---------- United States ----------
    us_keywords = [
        'united states',
        'united state',
        'u.s',
        'usa',
        'us of a',
        'the us',
        'the united states',
        'unitedstates'
    ]

    if any(k in country for k in us_keywords):
        return 'US'

    # ---------- United Kingdom ----------
    uk_keywords = [
        'united kingdom',
        'united kindom',
        'united kingdomk',
        'england',
        'wales',
        'northern ireland',
        'scotland',
        'u.k'
    ]

    if any(k in country for k in uk_keywords):
        return 'United Kingdom'

    # ---------- Canada ----------
    if 'canada' in country:
        return 'Canada'

    # ---------- Australia ----------
    if country.startswith('australi'):
        return 'Australia'

    # ---------- New Zealand ----------
    if 'new zealand' in country:
        return 'New Zealand'

    # ---------- Ireland ----------
    if country in ['ireland', 'republic of ireland']:
        return 'Ireland'

    # ---------- India ----------
    if 'india' == country:
        return 'India'

    # ---------- Germany ----------
    if 'germany' in country:
        return 'Germany'

    # ---------- Netherlands ----------
    if 'netherlands' in country:
        return 'Netherlands'

    # ---------- UAE ----------
    if 'united arab emirates' in country:
        return 'United Arab Emirates'

    # Default
    return country.title()

In [37]:
df['country_clean'] = df['country'].apply(clean_country)

In [38]:
df['country_clean'].value_counts()

country_clean
Us                21542
Canada             1678
US                 1512
United Kingdom     1471
Australia           390
                  ...
Liberia               1
1                     1
Nigeria + Uk          1
Zambia                1
Unknown               1
Name: count, Length: 201, dtype: int64

In [39]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [40]:
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day
df['year'] = df['timestamp'].dt.year
df['time'] = df['timestamp'].dt.time

In [41]:
df['month'] = df['timestamp'].dt.month_name()

In [42]:
df.head()

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,country,state,...,field_experience_years,education_level,gender,race,race_clean,country_clean,month,day,year,time
0,2021-04-27 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,Unknown,55000,0.0,USD,US,Massachusetts,...,5-7 years,Master's degree,Woman,White,White,Us,April,27,2021,11:02:10
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,Unknown,54600,4000.0,GBP,United Kingdom,Unknown,...,5-7 years,College degree,Non-binary,White,White,United Kingdom,April,27,2021,11:02:22
2,2021-04-27 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,Unknown,34000,0.0,USD,US,Tennessee,...,2 - 4 years,College degree,Woman,White,White,Us,April,27,2021,11:02:38
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,Unknown,62000,3000.0,USD,US,Wisconsin,...,5-7 years,College degree,Woman,White,White,Us,April,27,2021,11:02:41
4,2021-04-27 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,Unknown,60000,7000.0,USD,US,South Carolina,...,5-7 years,College degree,Woman,White,White,Us,April,27,2021,11:02:42

In [43]:
df["field_experience_years"].value_counts(dropna=False).sort_index()

field_experience_years
1 year or less      1540
11 - 20 years       6513
2 - 4 years         6249
21 - 30 years       1864
31 - 40 years        382
41 years or more      42
5-7 years           6497
8 - 10 years        4976
Name: count, dtype: int64

In [44]:
df["total_experience_years"].value_counts(dropna=False).sort_index()

total_experience_years
1 year or less       568
11 - 20 years       9588
2 - 4 years         3049
21 - 30 years       3630
31 - 40 years        867
41 years or more     126
5-7 years           4873
8 - 10 years        5362
Name: count, dtype: int64

# finally done

In [45]:
df.to_csv('datasets/cleaned_salary_survey.csv', index=False)